name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
#authenticacion dockerhub
#   - name: Docker Login
#     env:
#los secret configurados como varialble de entorno dentro de gitHub secrets
#      DOCKER_USER: 1234user o ${{secrets.DOCKER_USER}}
#      DOCKER_PASSWORD: 1234password o ${{secrets.DOCKER_PASSWORD}}
#     run: |
#      echo "Inicio Login"
#      docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
#      echo "Inicio Login"
#    - name: Build the Docker image
#      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    
