name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Git Semantic Version
      uses: PaulHatch/semantic-version@v4.0.3
      with:
        major_pattern: "major:"
        minor_pattern: "feat:"
        format: "${major}.${minor}.${patch}-prerelease${increment}"
      id: version
    - name: Muestra version
      env:
        ID_VERSION: ${{steps.version.outputs.version}}
      run: |
        echo "Nueva Version: $ID_VERSION !!!! "
#authenticacion dockerhub
#   - name: Docker Login
#     env:
#los secret configurados como varialble de entorno dentro de gitHub secrets
#      DOCKER_USER: 1234user o ${{secrets.DOCKER_USER}}
#      DOCKER_PASSWORD: 1234password o ${{secrets.DOCKER_PASSWORD}}
#     run: |
#      echo "Inicio Login"
#      docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
#      echo "Termina Login"
    - name: Build Docker image
      env:
        ID_VERSION: ${{steps.version.outputs.version}}
      run: |
        docker build -t graphql-git:$ID_VERSION .
        docker build -t graphql-git:latest .
# Paso para subir imagen al DockerHub, debe ser usuario registrado y que pase el login
#    - name: Push Docker image to DockerHub
#      run: |
#        docker push -t username/graphql-git:0.0.2
#        docker push -t username/graphql-git:latest
#    - name: Build the Docker image
#      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    
